### ISSUE TITLE
An error of 'clip_idx'  while testing?

### ISSUE THREAD

**Issue by Andy1621** [facebookresearch/SlowFast#124]
Hello, thanks for your codes of SlowFast.!!! These days I have tried to fine-tuing SlowFast in my own dataset, thus I needed to design my own dataset  class like Kinetics. I notice that in tesing, you sample some clips from a video uniformly for aggregating the prediction results (i.e. **cfg.TEST.NUM_ENSEMBLE_VIEWS**)
https://github.com/facebookresearch/SlowFast/blob/25a0f633b73fe2e1f9698f8a011dfc111828491b/slowfast/datasets/kinetics.py#L137
However, in `datasets/kitetics.py`  I find that 
```python
temporal_sample_index = (
    self._spatial_temporal_idx[index]
     // self.cfg.TEST.NUM_SPATIAL_CROPS
)
```
Why not 
```python
temporal_sample_index = (
    self._spatial_temporal_idx[index]
     // self.cfg.TEST.NUM_ENSEMBLE_VIEWS
)
```
Is it an error? BTW, there isn's an matched `if` for `else` in line 211.
https://github.com/facebookresearch/SlowFast/blob/25a0f633b73fe2e1f9698f8a011dfc111828491b/slowfast/datasets/kinetics.py#L211

**Comment by takatosp1** [comment]
Hi, thank you so much for playing with PySlowFast!!!
I am impressed that you could provide such a detailed description, thanks!

1) Regarding to `temporal_sample_index`: it is suppose to be a number range from 0 to 9, and self._spatial_temporal_idx[index] is range(30), so we should div(NUM_SPATIAL_CROPS) rather than div(TEST.NUM_ENSEMBLE_VIEWS)

2) Regarding to `else`: there is a clause called [`for/else`](https://book.pythontips.com/en/latest/for_-_else.html).

**Comment by Andy1621** [comment]
Thanks for your patience!!! I thought I have made some mistakes in `%` and `//`.... ￣□￣｜｜
Thanks again~~~
