### ISSUE TITLE
len(sys.argv) == 1 is no need when parsing the arguments

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [facebookresearch/SlowFast#13]
Thank you for your great work!

I notice that you set "opts" as only one positional argument and its default as None.
So. I believe you allow me to use this command without any arguments (automatically set as None).
However, once I execute the following command,

```
python tools/run_net.py
```

I got the following error.

```
usage: run_net.py [-h] [--shard_id SHARD_ID] [--num_shards NUM_SHARDS]
                  [--init_method INIT_METHOD] [--cfg CFG_FILE]
                  ...

Provide SlowFast video training and testing pipeline.

positional arguments:
  opts                  See slowfast/config/defaults.py for all options

optional arguments:
  -h, --help            show this help message and exit
  --shard_id SHARD_ID   The shard id of current node, Starts from 0 to
                        num_shards - 1
  --num_shards NUM_SHARDS
                        Number of shards using by the job
  --init_method INIT_METHOD
                        Initialization method, includes TCP or shared file-
                        system
  --cfg CFG_FILE        Path to the config file
```

This error occurs because you need us to set at least one arguments as below regardless of setting a default value:

```
if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
```

I would suggest that you removed these portions from the code so that we used the command without any arguments.

Thank you for your consideration!

**Comment by takatosp1** [comment]
Thanks for the kind suggestion!
The argument missing here is cfg, which is the path to the config file users need to provide. If no cfg is provided, the pipeline would not able to know what model do we want to play with.
There is instruction you could follow in
https://github.com/facebookresearch/SlowFast/blob/master/GETTING_STARTED.md

I will also consider your suggestion to have a config free way to start the job, however I do have the concern that it would be confusing to start job config freely, since it would be hard for the user to know what model they are playing with.
