### ISSUE TITLE
If I want to train a slow fast model with AVA 2.1 dataset, which config should be used and what is the training command?

### ISSUE THREAD

**Issue by sureone** [facebookresearch/SlowFast#147]
Is below a correct training command for this case?

```
python tools/run_net.py \
  --cfg configs/AVA/c2/SLOWFAST_32x2_R50.yaml \
  DATA.PATH_TO_DATA_DIR path_to_your_dataset \
  TEST.CHECKPOINT_FILE_PATH path_to_your_checkpoint \
  TRAIN.ENABLE False \
```

**Comment by takatosp1** [comment]
Hi
Thanks for playing with PySlowFast!
You might want to prepare the data following the instruction from (here)[https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md]
The config under c2 is supposed to be used for inference. You could instead use
```
configs/AVA/*.yaml
```
Otherwise the config looks good to me.
