### ISSUE TITLE
.csv files for Kinetics Dataset

### ISSUE THREAD

**Issue by 17Skye17** [facebookresearch/SlowFast#16]
Hi, Nice repo!
Could you please provide `train.csv, val.csv, test.csv` mentioned in` `DATASET.md` ?
Also if possible, could you share the link of your Kinetics dataset copy? Since many links are unavailable now. 

Thank you

**Comment by takatosp1** [comment]
Thanks for reaching out!
Because of the legal issue, we are not able to provide the dataset related code/ script, and we are not able to provide the copy of the data officially. I’ll talk to the legal team regarding to this issue.

You may leave some comment in the Kinetics dataset or ActivityNet github repo to see if they can provide some official data copy. Or you can reach out to your friends to see if they can share you some copy for non commercial use.

When you reach out to your friends, please consider me as one of your friend. :)

**Comment by Malithi-gif** [comment]
How make a train.csv file?
![image](https://user-images.githubusercontent.com/54534252/102626880-6b28aa80-416d-11eb-8dbd-dfcf078ff460.png)

Is this correct?

**Comment by wssxjtu** [comment]
请问您的问题解决了？可否告知我生成label文件的脚本该如何编写？

**Comment by wssxjtu** [comment]
> 您好，官方 test.csv 不提供标签信息。您能否简要介绍一下如何生成正确的 test.csv？非常感谢！

好像你的问题解决了？可否告知我生成标签文件的脚本如何编写？

**Comment by wssxjtu** [comment]
> 您好，官方 test.csv 不提供标签信息。您能否简要介绍一下如何生成正确的 test.csv？非常感谢！

请问您的问题是否解决？可否告知我生成标签文件的脚本如何编写？

**Comment by ZhangYushan3** [comment]
我是遍历了文件夹下所有的文件 然后吧路径和label存在.csv文件里--发自新浪邮箱客户端
在 10月30日 15:42，wssxjtu ***@***.***> 写道：


请问您的问题解决了？可否告知我生成label文件的脚本该如何编写？



&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhangYushan3** [comment]
test部分没有标签不知道怎么生成--发自新浪邮箱客户端
在 10月30日 15:42，wssxjtu ***@***.***> 写道：




您好，官方 test.csv 不提供标签信息。您能否简要介绍一下如何生成正确的 test.csv？非常感谢！



好像你的问题解决了？可否告知我生成标签文件的脚本如何编写？



&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
