### ISSUE TITLE
No instructions for using this package?

### ISSUE THREAD

**Issue by yaoliUoA** [facebookresearch/SlowFast#4]
After install the package, I found that there are a lot of missing instruction information for this packge, for example, 
1. How to prepare the training data from benchmark datasets. 
2. Example commands to train the networks. 
3. Example commands to test the networks.

**Comment by takatosp1** [comment]
Hi, thanks for using the code. 
Regarding to 1), we have provided the instruction of data preparation, and you may find the instruction under `slowfast/datasets/DATASET.md`.
Regarding to 2) and 3), you may simple try python tools/run_net.py.

**Comment by Israrulhaq190** [comment]
> Hi, thanks for using the code.
> Regarding to 1), we have provided the instruction of data preparation, and you may find the instruction under `slowfast/datasets/DATASET.md`. Because of the legal issue, we can not share any script related to data downloading.
> Regarding to 2) and 3), you may simple try python tools/run_net.py.


There are several things to discuss in order to run the testing. Because when I try:
python tools/run_net.py

usage: run_net.py [-h] [--shard_id SHARD_ID] [--num_shards NUM_SHARDS]
                  [--init_method INIT_METHOD] [--cfg CFG_FILE]
                  ...

Provide SlowFast video training and testing pipeline.

positional arguments:
  opts                  See slowfast/config/defaults.py for all options

optional arguments:
  -h, --help            show this help message and exit
  --shard_id SHARD_ID   The shard id of current node, Starts from 0 to
                        num_shards - 1
  --num_shards NUM_SHARDS
                        Number of shards using by the job
  --init_method INIT_METHOD
                        Initialization method, includes TCP or shared file-
                        system
  --cfg CFG_FILE        Path to the config file

**Comment by takatosp1** [comment]
You may find more details here: https://github.com/facebookresearch/SlowFast/issues/13
