### ISSUE TITLE
Question about selective decoding and video meta information

### ISSUE THREAD

**Issue by bryanyzhu** [facebookresearch/SlowFast#40]
Hi, thank you for the great codebase. I was reading the code on dataloader. It seems that from [this line](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/kinetics.py#L97), all the meta information is an empty dictionary. So if this is the case, are we still doing selective decoding?

And BTW, could you explain more on what is selective decoding and what is its advantage? Thank you very much.

**Comment by takatosp1** [comment]
Hi,
Thanks for using the codebase. The PySlowFast supported two ways of decoding, one depends pyAV and another depends on TorchVision (TV). Because of the dependency issue in TV (ffmpeg), we are holding releasing the TV based decoding, which will use meta info as your referred in the link.
Selective decoding is based on seek, which will reduce the time of decoding.
