### ISSUE TITLE
ModuleNotFoundError: No module named 'vision'

### ISSUE THREAD

**Issue by yancccc** [facebookresearch/SlowFast#718]
(action) ps@ps:~/ycc/SlowFast-main$ python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
/home/ps/anaconda3/envs/action/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/home/ps/anaconda3/envs/action/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ps/ycc/SlowFast-main/tools/run_net.py", line 8, in <module>
    from vision.fair.slowfast.tools.demo_net import demo
ModuleNotFoundError: No module named 'vision'

**Comment by SixteenVanish** [comment]
I also encountered this problem. How did you solve it?

**Comment by Gerry048** [comment]
slowfast) gerry@GerrydeMacBook-Pro slowfast % python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
/Users/gerry/Desktop/conda/anaconda3/envs/slowfast/lib/python3.8/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/Users/gerry/Desktop/conda/anaconda3/envs/slowfast/lib/python3.8/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "tools/run_net.py", line 8, in <module>
    from vision.fair.slowfast.tools.demo_net import demo
ModuleNotFoundError: No module named 'vision'

**Comment by yangdd01** [comment]
How'd you fix it, bro.

**Comment by ConvAndConv** [comment]
I encountered the same problem, how did you solve it?

**Comment by yangdd01** [comment]
It's been a few days. I kind of forgot. It seems that updating one of the dependent versions is enough


---Original---
From: ***@***.***&gt;
Date: Thu, Sep 12, 2024 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/SlowFast] ModuleNotFoundError: No module named'vision' (Issue #718)




 
I encountered the same problem, how did you solve it?

**Comment by tomatoyou** [comment]
代码是不是更新了，我用之前的替换了一下：
from demo_net import demo
from test_net import test
from train_net import train
from visualization import visualize

**Comment by yangdd01** [comment]
我之前试的时候发现了，不过还是谢谢你！



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 14, 2024 19:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/SlowFast] ModuleNotFoundError: No module named'vision' (Issue #718)




 
代码是不是更新了，我用之前的替换了一下：
 from demo_net import demo
 from test_net import test
 from train_net import train
 from visualization import visualize

**Comment by naokedaduan** [comment]
E:\anconda\envs\slowfast\lib\site-packages\torchvision\transforms\_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
E:\anconda\envs\slowfast\lib\site-packages\torchvision\transforms\_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "D:\pycharm\SlowFast\slowfast\tools\run_net.py", line 8, in <module>
    from vision.fair.slowfast.tools.demo_net import demo
ModuleNotFoundError: No module named 'vision'       
please help me

**Comment by yangdd01** [comment]
It's been a bit longer. Two files seem to be calling back to a previous version.


---Original---
From: ***@***.***&gt;
Date: Sun, Sep 15, 2024 15:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/SlowFast] ModuleNotFoundError: No module named'vision' (Issue #718)




 
E:\anconda\envs\slowfast\lib\site-packages\torchvision\transforms_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
 warnings.warn(
 E:\anconda\envs\slowfast\lib\site-packages\torchvision\transforms_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
 warnings.warn(
 Traceback (most recent call last):
 File "D:\pycharm\SlowFast\slowfast\tools\run_net.py", line 8, in 
 from vision.fair.slowfast.tools.demo_net import demo
 ModuleNotFoundError: No module named 'vision'
 please help me

**Comment by farazBhatti** [comment]
you might have missed something during installation. A work around is


```
from demo_net import demo
from test_net import test
from train_net import train
from visualization import visualize
```
instead of 
```
 from vision.fair.slowfast.tools.demo_net import demo
 from vision.fair.slowfast.tools.test_net import test
 from vision.fair.slowfast.tools.train_net import train
from vision.fair.slowfast.tools.visualization import visualize
```

**Comment by naokedaduan** [comment]
> 在安装过程中，您可能遗漏了某些内容。解决方法是
> 
> ```
> from demo_net import demo
> from test_net import test
> from train_net import train
> from visualization import visualize
> ```
> 
> 而不是
> 
> ```
>  from vision.fair.slowfast.tools.demo_net import demo
>  from vision.fair.slowfast.tools.test_net import test
>  from vision.fair.slowfast.tools.train_net import train
> from vision.fair.slowfast.tools.visualization import visualize
> ```

thanks
