### ISSUE TITLE
weights shape not matched when using pretrained SLOWFAST_8x8_R50

### ISSUE THREAD

**Issue by dhlrd** [facebookresearch/SlowFast#8]
when using pretrained model SLOWFAST_8x8_R50 to train model, it occurs with the following error:

AssertionError: t_res4_5_branch2c_bn_subsample_w: (256, 128, 7, 1, 1) does not match s4_fuse.conv_f2s.weight: (256, 128, 5, 1, 1)

**Comment by takatosp1** [comment]
Hi,
Thanks for using the pretrained model! 
In `https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md` you will see the related configs paired with the pretrained model. Then you'll see the config you shall use is `Kinetics/c2/SLOWFAST_8x8_R50.yaml` rather than `Kinetics/SLOWFAST_8x8_R50.yaml`.
So long story short, you are using a wrong config now, you can go ahead to use the config under c2 folder. :)
